### ISSUE TITLE
No license given

### ISSUE THREAD

**Issue by RaphaelWimmer** [aguaviva/micro-jpeg-visualizer#2]
Hi. Would you mind adding a license to your code? (something liberal, such as CC-0 or MIT license would be great)

**Comment by aguaviva** [comment]
Done! (I just saw your entry!) What were you after a license? I am curious :)

**Comment by RaphaelWimmer** [comment]
Thanks. I wanted/want  to modify your script in order to understand JPEG compression better and to output  intermediate steps that I could use as examples in a course on digital media which I teach in the winter semester. I feel better modifying code when I know that I'm allowed to republish the modifications. I'll probably have a look at your code next winter when/if I'll teach the same course again. Thank you!
