### ISSUE TITLE
Status enquiry

### ISSUE THREAD

**Issue by mittalgovind** [aguaviva/micro-jpeg-visualizer#5]
Is this repo accepting pull requests? I have expanded the code to work for various chroma subsampling also. Initially it was working for 1x1 only but now I can make it work for 1x2, 2x1 and 2x2 also.

**Comment by AyonDebnath** [comment]
> Is this repo accepting pull requests? I have expanded the code to work for various chroma subsampling also. Initially it was working for 1x1 only but now I can make it work for 1x2, 2x1 and 2x2 also.

@mittalgovind Do you have the expanded code available? I am trying to expand the code to work for other chroma subsamples.

**Comment by aguaviva** [comment]
I rather keep this repo simple as this is just for educational purposes. But feel free to fork and extend it, I will link to it
